package org.com.myapp.entity;
// Generated Apr 29, 2015 4:25:15 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Competition generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="competition"
    ,catalog="crossworddb"
)
public class Competition  implements java.io.Serializable {


     private Integer idCompetition;
     private String name;
     private String note;
     private Date begin;
     private Date end;
     private Date createDate;
     private Boolean isActive;
     private Set<Match> matches = new HashSet<Match>(0);

    public Competition() {
    }

    public Competition(String name, String note, Date begin, Date end, Date createDate, Boolean isActive, Set<Match> matches) {
       this.name = name;
       this.note = note;
       this.begin = begin;
       this.end = end;
       this.createDate = createDate;
       this.isActive = isActive;
       this.matches = matches;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdCompetition", unique=true, nullable=false)
    public Integer getIdCompetition() {
        return this.idCompetition;
    }
    
    public void setIdCompetition(Integer idCompetition) {
        this.idCompetition = idCompetition;
    }

    
    @Column(name="Name", length=256)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Note", length=256)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Begin", length=19)
    public Date getBegin() {
        return this.begin;
    }
    
    public void setBegin(Date begin) {
        this.begin = begin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="End", length=19)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="isActive")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="competition")
    public Set<Match> getMatches() {
        return this.matches;
    }
    
    public void setMatches(Set<Match> matches) {
        this.matches = matches;
    }




}


