package org.com.myapp.entity;
// Generated Apr 25, 2015 9:03:17 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Item generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="item"
    ,catalog="crossworddb"
)
public class Item  implements java.io.Serializable {


     private Integer idItem;
     private String question;
     private String answer;
     private Integer count;
     private Date createDate;
     private Set<Match> matches = new HashSet<Match>(0);

    public Item() {
    }

    public Item(String question, String answer, Integer count, Date createDate, Set<Match> matches) {
       this.question = question;
       this.answer = answer;
       this.count = count;
       this.createDate = createDate;
       this.matches = matches;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdItem", unique=true, nullable=false)
    public Integer getIdItem() {
        return this.idItem;
    }
    
    public void setIdItem(Integer idItem) {
        this.idItem = idItem;
    }

    
    @Column(name="Question", length=256)
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }

    
    @Column(name="Answer", length=45)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    
    @Column(name="Count")
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="itemsinmatches", catalog="crossworddb", joinColumns = { 
        @JoinColumn(name="IdItem", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="IdMatch", nullable=false, updatable=false) })
    public Set<Match> getMatches() {
        return this.matches;
    }
    
    public void setMatches(Set<Match> matches) {
        this.matches = matches;
    }




}


