package org.com.myapp.entity;
// Generated Apr 25, 2015 9:03:17 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membership generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="membership"
    ,catalog="crossworddb"
)
public class Membership  implements java.io.Serializable {


     private int idUser;
     private String confirmationToken;
     private Boolean isConfirmed;
     private Date lastPasswordFailureDate;
     private Integer passwordFailuresSinceLastSuccess;
     private String password;
     private Date passwordChangedDate;
     private String passwordSalt;
     private String passwordVerificationToken;
     private Date passwordVerificationTokenExpirationDate;
     private Date createDate;

    public Membership() {
    }

	
    public Membership(int idUser, String password, String passwordSalt) {
        this.idUser = idUser;
        this.password = password;
        this.passwordSalt = passwordSalt;
    }
    public Membership(int idUser, String confirmationToken, Boolean isConfirmed, Date lastPasswordFailureDate, Integer passwordFailuresSinceLastSuccess, String password, Date passwordChangedDate, String passwordSalt, String passwordVerificationToken, Date passwordVerificationTokenExpirationDate, Date createDate) {
       this.idUser = idUser;
       this.confirmationToken = confirmationToken;
       this.isConfirmed = isConfirmed;
       this.lastPasswordFailureDate = lastPasswordFailureDate;
       this.passwordFailuresSinceLastSuccess = passwordFailuresSinceLastSuccess;
       this.password = password;
       this.passwordChangedDate = passwordChangedDate;
       this.passwordSalt = passwordSalt;
       this.passwordVerificationToken = passwordVerificationToken;
       this.passwordVerificationTokenExpirationDate = passwordVerificationTokenExpirationDate;
       this.createDate = createDate;
    }
   
     @Id 

    
    @Column(name="IdUser", unique=true, nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="ConfirmationToken", length=145)
    public String getConfirmationToken() {
        return this.confirmationToken;
    }
    
    public void setConfirmationToken(String confirmationToken) {
        this.confirmationToken = confirmationToken;
    }

    
    @Column(name="IsConfirmed")
    public Boolean getIsConfirmed() {
        return this.isConfirmed;
    }
    
    public void setIsConfirmed(Boolean isConfirmed) {
        this.isConfirmed = isConfirmed;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastPasswordFailureDate", length=19)
    public Date getLastPasswordFailureDate() {
        return this.lastPasswordFailureDate;
    }
    
    public void setLastPasswordFailureDate(Date lastPasswordFailureDate) {
        this.lastPasswordFailureDate = lastPasswordFailureDate;
    }

    
    @Column(name="PasswordFailuresSinceLastSuccess")
    public Integer getPasswordFailuresSinceLastSuccess() {
        return this.passwordFailuresSinceLastSuccess;
    }
    
    public void setPasswordFailuresSinceLastSuccess(Integer passwordFailuresSinceLastSuccess) {
        this.passwordFailuresSinceLastSuccess = passwordFailuresSinceLastSuccess;
    }

    
    @Column(name="Password", nullable=false, length=128)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PasswordChangedDate", length=19)
    public Date getPasswordChangedDate() {
        return this.passwordChangedDate;
    }
    
    public void setPasswordChangedDate(Date passwordChangedDate) {
        this.passwordChangedDate = passwordChangedDate;
    }

    
    @Column(name="PasswordSalt", nullable=false, length=128)
    public String getPasswordSalt() {
        return this.passwordSalt;
    }
    
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    
    @Column(name="PasswordVerificationToken", length=128)
    public String getPasswordVerificationToken() {
        return this.passwordVerificationToken;
    }
    
    public void setPasswordVerificationToken(String passwordVerificationToken) {
        this.passwordVerificationToken = passwordVerificationToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PasswordVerificationTokenExpirationDate", length=19)
    public Date getPasswordVerificationTokenExpirationDate() {
        return this.passwordVerificationTokenExpirationDate;
    }
    
    public void setPasswordVerificationTokenExpirationDate(Date passwordVerificationTokenExpirationDate) {
        this.passwordVerificationTokenExpirationDate = passwordVerificationTokenExpirationDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


