package org.com.myapp.entity;
// Generated Apr 25, 2015 9:03:17 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ScoreId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ScoreId  implements java.io.Serializable {


     private int idUser;
     private int idMatch;

    public ScoreId() {
    }

    public ScoreId(int idUser, int idMatch) {
       this.idUser = idUser;
       this.idMatch = idMatch;
    }
   


    @Column(name="IdUser", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    @Column(name="IdMatch", nullable=false)
    public int getIdMatch() {
        return this.idMatch;
    }
    
    public void setIdMatch(int idMatch) {
        this.idMatch = idMatch;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScoreId) ) return false;
		 ScoreId castOther = ( ScoreId ) other; 
         
		 return (this.getIdUser()==castOther.getIdUser())
 && (this.getIdMatch()==castOther.getIdMatch());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUser();
         result = 37 * result + this.getIdMatch();
         return result;
   }   


}


