package org.com.myapp.entity;
// Generated Apr 25, 2015 9:03:17 PM by Hibernate Tools 3.6.0


import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Score generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name="score"
    ,catalog="crossworddb"
)
public class Score  implements java.io.Serializable {


     private ScoreId id;
     private Match match;
     private User user;
     private Float point;
     private Float time;
     private String unit;
     private Date createDate;

    public Score() {
    }

	
    public Score(ScoreId id, Match match, User user) {
        this.id = id;
        this.match = match;
        this.user = user;
    }
    public Score(ScoreId id, Match match, User user, Float point, Float time, String unit, Date createDate) {
       this.id = id;
       this.match = match;
       this.user = user;
       this.point = point;
       this.time = time;
       this.unit = unit;
       this.createDate = createDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idUser", column=@Column(name="IdUser", nullable=false) ), 
        @AttributeOverride(name="idMatch", column=@Column(name="IdMatch", nullable=false) ) } )
    public ScoreId getId() {
        return this.id;
    }
    
    public void setId(ScoreId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdMatch", nullable=false, insertable=false, updatable=false)
    public Match getMatch() {
        return this.match;
    }
    
    public void setMatch(Match match) {
        this.match = match;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdUser", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="Point", precision=12, scale=0)
    public Float getPoint() {
        return this.point;
    }
    
    public void setPoint(Float point) {
        this.point = point;
    }

    
    @Column(name="Time", precision=12, scale=0)
    public Float getTime() {
        return this.time;
    }
    
    public void setTime(Float time) {
        this.time = time;
    }

    
    @Column(name="Unit", length=45)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CreateDate", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


