package org.com.myapp.model;

//Generated Apr 25, 2015 9:03:17 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Competition generated by hbm2java
 */
@SuppressWarnings("serial")
public class CompetitionData implements java.io.Serializable {

	private Integer idCompetition;
	private String name;
	private String note;
	private Date begin;
	private Date end;
	private Date createDate;

	public CompetitionData() {
	}

	public CompetitionData(String name, String note, Date begin, Date end,
			Date createDate) {
		this.name = name;
		this.note = note;
		this.begin = begin;
		this.end = end;
		this.createDate = createDate;
	}

	public Integer getIdCompetition() {
		return this.idCompetition;
	}

	public void setIdCompetition(Integer idCompetition) {
		this.idCompetition = idCompetition;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
